# Generated by Django 4.2.14 on 2024-07-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones_sirgas_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionsirgas',
            name='monument_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estacionsirgas',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estacionsirgas',
            name='province',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
