# Generated by Django 4.2.14 on 2024-07-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones_sirgas_backend', '0002_alter_estacionsirgas_monument_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionsirgas',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
